### ISSUE TITLE
The mirror span is still read by screen readers

### ISSUE THREAD

**Issue by lenzls** [syropian/vue-input-autowidth#13]
The auto generated mirror span is read by screen readers.

Related merge request: #12

**Comment by syropian** [comment]
Fixed in #12

**Comment by lenzls** [comment]
I'm still getting the old version without the merge request.

Probably because I didn't update the `dist` folder?

I thought this will be taken care of in the release process or something :)
